
MONKE = {
  t: {
    legend: 'Select a monke (archetype)',
    options: [
       'albino small',
       'brown',
       'dark small',
       'gray small',
       'gray',
       'green small',
       'green',
       'greener orc', 
       'greener', 
       'light small',
       'medium small',
       'pink small',
       'pink',
       'purple small',
       'purple',
       'red',
       'white',
       'alien',
       'boned', 
       'bot', 
       'deathbot', 
       'demon', 
       'golden', 
       'gold orc', 
       'gold', 
       'hyena', 
       'mempool', 
       'pepe block', 
       'pepe', 
       'rainbow', 
       'safemode', 
       'zombie', 
       'blue orc', 
       'blue', 
       'orange orc', 
       'orange', 
       'orange 2 orc', 
       'orange 2', 
       'squiggle', 
       'black', 
    ]
  },

  eyes: {
    legend: 'Select eyes (or eyewear)',
    none: true,
    options: [
      'eyes left', 
      'eyes right', 
      'eyes big', 
      'eyes bored', 
      'eyes bot', 
      'eyes bot green', 
      'eyes deathbot', 
      'eyes monobrow', 
      'eyes pepe', 
      'eyes zombie', 
      '3d glasses', 
      'shades blend', 
      'shades rainbow', 
      'shades polarized', 
      'shades cool', 
      'eyepatch', 
      'eyemask', 
      'vr', 
      'lasereyes red', 
      'lasereyes blue', 
      'lasereyes green', 
      'lasereyes gold', 
     ],
  },

  hair: {
    legend: 'Select hair',
    none: true,
    options: [
      'mohawk', 
      'mohawk blonde', 
      'mohawk green', 
      'mohawk purple', 
      'mohawk red', 
      'mohawk 2', 
      'mohawk 2 blonde', 
      'mohawk 2 green', 
      'mohawk 2 purple', 
      'mohawk 2 red', 
      'mohawk 2 orange', 
      'mohawk 2 pink', 
      'peakspike', 
      'peakspike purple', 
      'peakspike red', 
      'peakspike blonde', 
    ],
  },


  headwear: {
    legend: 'Select headwear (or hoodie)',
    none: true,
    options: [
       'bandana', 
       'bandana 2', 
       'bowler', 
       'cap army', 
       'cap mcb', 
       'cap ordinal', 
       'cap safemode', 
       'cap terminal', 
       'cap terminal 2', 
       'cap captain', 
       'cap', 
       'cowboy hat', 
       'crown', 
       'fez', 
       'flat hat', 
       'french cap', 
       'knitted cap', 
       'knitted cap 2', 
       'police cap', 
       'beanie', 
       'cap burger king', 
       'cap mcd black', 
       'cap mcd red', 
       'cap mcd white', 
       'cap subway', 
       'jesterhat', 
       'helmet', 
       'helmet 2', 
       'top hat', 
       'top hat midnight', 
       'wizard hat', 
       'wizardhat orange', 
       'wizardhat red', 
       'wizardhat midnight', 
       'wizardhat gold', 
       'wizardhat white', 
       'headband', 
       'halo', 
       'hoodie', 
       'hoodie midnight', 
       'hoodie indigo', 
       'hoodie blue', 
       'hoodie cobalt', 
       'hoodie aqua', 
       'hoodie green', 
       'hoodie greener', 
       'hoodie limegreen', 
       'hoodie gold', 
       'hoodie orange', 
       'hoodie ruby', 
       'hoodie red', 
       'hoodie purple', 
       'hoodie pink', 
         ]
  },
}

