
ROCK = {
  t: {
    legend: 'Select a rock (archetype)',
    options: [
      'albino', 
      'brown', 
      'dark', 
      'demon', 
      'golden', 
      'golden block', 
      'gray', 
      'gray block', 
      'green', 
      'memepool', 
      'pepe', 
      'alien', 
      'deathbot', 
      'safemode', 
      'pink', 
      'zombie', 
      'black',  
    ]
  },

  eyes: {
    legend: 'Select eyes (or eyewear)',
    none: true,
    options: [
      'eyes left', 
      'eyes big', 
      'eyes bored', 
      'eyes green', 
      'eyes red', 
      'eyes blue',
      'eyes monobrow', 
      'eyes pepe', 
      'eyes zombie', 
      '3d glasses', 
      'eyes polarized', 
      'eyes rainbow', 
      'eyes blend', 
      'eyes cool', 
      'lasereyes red', 
      'lasereyes green', 
      'lasereyes blue', 
      'lasereyes gold', 
      'vr',       
     ],
  },

  hair: {
    legend: 'Select hair',
    none: true,
    options: [
      'mohawk', 
      'mohawk blonde', 
      'mohawk purple', 
      'mohawk red', 
      'mohawk 2', 
      'mohawk 2 green', 
      'mohawk 2 pink', 
      'mohawk 2 red', 
      'peakspike', 
      'peakspike blonde', 
      'peakspike purple', 
      'peakspike red', 
      'wildhair', 
      'wildhair blonde', 
      'wildhair red', 
      'wildhair white', 
      'bob blonde', 
        ],
  },


  headwear: {
    legend: 'Select headwear',
    none: true,
    options: [
      'bandana', 
      'bandana 2', 
      'cowboy hat', 
      'headband', 
      'knitted cap', 
      'knitted cap 2', 
      'top hat', 
      'cap', 
      'cap mcb', 
      'cap mcd red', 
      'cap mcd white', 
      'cap mcd black', 
      'cap burger king', 
      'cap subway', 
      'crown', 
      'halo', 
     ]
  },
}

